flights_encoded <- read.csv("/Users/valentinalaugeri/Documents/LSE/ST446/project-2024-group-5/selected_flights_one_hot_encoded.csv")

popular_airlines <- c('Turkish Airlines', 'Malaysia Airlines', 'Singapore Airlines', 'Lufthansa', 'Qatar Airways', 'Emirates', 'Etihad', 'British Airways', ' Air India', ' ANA', 'Air France', ' Qantas', 'Emirates', 'EgyptAir', ' LATAM', ' Iberia', ' Air Canada', ' Lufthansa', ' United', ' SWISS', 'Iberia', 'British Airways', ' Air France', 'Air Canada', ' Austrian', ' KLM', ' Delta', ' American', ' EgyptAir', ' Turkish Airlines', 'Saudia', ' Brussels Airlines', 'LATAM', ' COPA', 'Gol', ' Avianca', ' Tap Air Portugal', 'Qantas', 'Virgin Australia', 'United', 'Delta', 'Singapore Airlines', 'Etihad', 'ANA', 'Cathay Pacific', ' Qatar Airways', ' SAS', ' Ethiopian', 'Austrian', 'SWISS', 'KLM', 'Aegean', 'Tap Air Portugal', 'Ethiopian', 'Aer Lingus', 'American', 'Avianca', 'COPA', 'WestJet', 'China Eastern', 'China Southern')

popular_airlines <- trimws(popular_airlines, "left")


all_airlines <- c(' ANA',
	' ASKY',
	' ASL Airlines',
	' AccesRail',
	' Advanced Air',
	' Aegean',
	' Aer Lingus',
	' Aeroflot',
	' Aerolineas Argentinas',
	' Aeromar',
	' Aeromexico',
	' Air Albania',
	' Air Algerie',
	' Air Arabia',
	' Air Arabia Egypt',
	' Air Arabia Maroc',
	' Air Astana',
	' Air Baltic',
	' Air Botswana',
	' Air Cairo',
	' Air Canada',
	' Air China',
	' Air Corsica',
	' Air Dolomiti',
	' Air Europa',
	' Air France',
	' Air India',
	' Air Macau',
	' Air Mauritius',
	' Air New Zealand',
	' Air Niugini',
	' Air Serbia',
	' Air Seychelles',
	' Air Tahiti Nui',
	' Air Transat',
	' Air-India Express',
	' AirAsia',
	' AirAsia (India)',
	' Aircalin',
	' Airlink',
	' Al Masria Universal Airlines',
	' Alaska',
	' Allegiant',
	' American',
	' Asiana',
	' Austrian',
	' Avianca',
	' Azerbaijan Airlines',
	' Azores Airlines',
	' Azul',
	' Bahamasair',
	' Bamboo Airways',
	' Bangkok Airways',
	' Belavia',
	' Biman',
	' Blue Air',
	' BoA',
	' British Airways',
	' Brussels Airlines',
	' Bulgaria Air',
	' COPA',
	' CSA',
	' Caribbean Airlines',
	' Cathay Pacific',
	' Cayman Airways',
	' CemAir Pty',
	' China Airlines',
	' China Eastern',
	' China Southern',
	' Condor',
	' Corendon',
	' Corendon Airlines Europe',
	' Croatia',
	' Cyprus Airways',
	' Delta',
	' EVA Air',
	' Eastern Airways',
	' Edelweiss Air',
	' EgyptAir',
	' El Al',
	' Emirates',
	' Ethiopian',
	' Etihad',
	' Eurowings',
	' Eurowings Discover',
	' F.B. Lineas Aereas',
	' Fiji Airways',
	' Finnair',
	' Firefly',
	' Flair Airlines',
	' FlyEgypt',
	' FlySafair',
	' Flybe',
	' Flynas',
	' Flyr AS',
	' Freebird Airlines',
	' Frontier',
	' GO FIRST',
	' Garuda Indonesia',
	' Gol',
	' Gulf Air',
	' Hainan',
	' Hawaiian',
	' Helvetic',
	' Hong Kong Airlines',
	' Hong Kong Express',
	' ITA',
	' Iberia',
	' Iberojet',
	' Icelandair',
	' IndiGo',
	' Indonesia AirAsia',
	' JAL',
	' Jazeera',
	' Jeju Air',
	' Jet2',
	' JetBlue',
	' Jetstar',
	' Jin Air',
	' Juneyao Airlines',
	' KLM',
	' Kenya Airways',
	' Korean Air',
	' Kuwait Airways',
	' LATAM',
	' LIFT operated as Global Aviation',
	' LOT',
	' Loganair',
	' Lufthansa',
	' Luxair',
	' Lynx Air',
	' MEA',
	' Malaysia Airlines',
	' Malindo Air',
	' Neos',
	' Nile Air',
	' Norwegian',
	' Nouvelair Tunisie',
	' Olympic',
	' Oman Air',
	' Orbest',
	' PLAY',
	' Pacific Airways',
	' Paranair',
	' Pegasus',
	' Philippine Airlines',
	' Philippines AirAsia',
	' Porter Airlines',
	' Qantas',
	' Qatar Airways',
	' Rex',
	' Royal Air Maroc',
	' Royal Brunei',
	' Royal Jordanian',
	' RwandAir',
	' S7',
	' SAS',
	' SNCF',
	' SWISS',
	' SalamAir',
	' Saudia',
	' Scoot',
	' Shandong',
	' Shanghai Airlines',
	' Shenzhen',
	' Sichuan Airlines',
	' Silver Airways',
	' Singapore Airlines',
	' Sky Airline',
	' Sky Express',
	' Skymark',
	' Smartwings',
	' South African',
	' SpiceJet',
	' SriLankan',
	' Star Flyer',
	' Sun Country Airlines',
	' SunExpress',
	" T'Way Air",
	' TAAG',
	' TAR Aerolineas',
	' TAROM',
	' THAI',
	' TUI Airways',
	' TUI fly',
	' Tap Air Portugal',
	' Thai Smile',
	' Transavia',
	' Tunisair',
	' Turkish Airlines',
	' United',
	' VOEPASS',
	' VietJet Air',
	' Vietnam Airlines',
	' Virgin Atlantic',
	' Virgin Australia',
	' Vistara',
	' Viva Air',
	' VivaAerobus',
	' Volaris',
	' Volotea',
	' Vueling',
	' WestJet',
	' Wideroe',
	' Wingo',
	' Wizz Air',
	' World 2 Fly',
	' XiamenAir',
	' ZIPAIR Tokyo',
	' Zambia Airways (2014)',
	' easyJet',
	' flydubai',
	' kulula',
	'ANA',
	'ASL Airlines',
	'Aegean',
	'Aer Lingus',
	'Aerolineas Argentinas',
	'Aeromexico',
	'Air Algerie',
	'Air Arabia',
	'Air Arabia Maroc',
	'Air Astana',
	'Air Austral',
	'Air Baltic',
	'Air Cairo',
	'Air Canada',
	'Air China',
	'Air Dolomiti',
	'Air Europa',
	'Air France',
	'Air India',
	'Air Macau',
	'Air Malta',
	'Air Mauritius',
	'Air Moldova',
	'Air New Zealand',
	'Air Niugini',
	'Air Serbia',
	'Air Tahiti Nui',
	'Air Transat',
	'Air-India Express',
	'AirAsia (India)',
	'Aircalin',
	'American',
	'Arkia',
	'Asiana',
	'Atlantic Airways',
	'Austrian',
	'Avianca',
	'Azores Airlines',
	'Azul',
	'Bamboo Airways',
	'Biman',
	'Blue Air',
	'BoA',
	'British Airways',
	'Brussels Airlines',
	'Bulgaria Air',
	'COPA',
	'CSA',
	'Caribbean Airlines',
	'Cathay Pacific',
	'Cebu Pacific',
	'China Airlines',
	'China Eastern',
	'China Southern',
	'Condor',
	'Corendon Airlines Europe',
	'Croatia',
	'Cyprus Airways',
	'Delta',
	'EVA Air',
	'EgyptAir',
	'Emirates',
	'Ethiopian',
	'Etihad',
	'Eurowings',
	'Eurowings Discover',
	'Fiji Airways',
	'Finnair',
	'Flair Airlines',
	'Fly One',
	'Flynas',
	'Flyr AS',
	'GO FIRST',
	'Garuda Indonesia',
	'Gol',
	'Gulf Air',
	'Hainan',
	'Hawaiian',
	'HiSky Europe SRL',
	'Hong Kong Airlines',
	'ITA',
	'Iberia',
	'Iberia Express',
	'Icelandair',
	'IndiGo',
	'JAL',
	'Jazeera',
	'Jet2',
	'Jetstar',
	'Juneyao Airlines',
	'KLM',
	'Kenya Airways',
	'Korean Air',
	'Kuwait Airways',
	'LATAM',
	'LOT',
	'Lufthansa',
	'Lufthansa CityLine',
	'Luxair',
	'Lynx Air',
	'MEA',
	'Malaysia Airlines',
	'Neos',
	'Nile Air',
	'Norwegian',
	'Nouvelair Tunisie',
	'Oman Air',
	'PLAY',
	'Pacific Airways',
	'Pakistan',
	'Paranair',
	'Pegasus',
	'Philippine Airlines',
	'Qantas',
	'Qatar Airways',
	'Rex',
	'Royal Air Maroc',
	'Royal Brunei',
	'Royal Jordanian',
	'SAS',
	'SNCF',
	'SWISS',
	'Saudia',
	'Scoot',
	'Shandong',
	'Shanghai Airlines',
	'Shenzhen',
	'Sichuan Airlines',
	'Singapore Airlines',
	'Sky Airline',
	'Sky Express',
	'SpiceJet',
	'SriLankan',
	'SunExpress',
	'Sunwing',
	'Swoop',
	'TAAG',
	'TAROM',
	'THAI',
	'TUI fly',
	'Tap Air Portugal',
	'Transavia',
	'Tunisair',
	'Turkish Airlines',
	'Tus Air',
	'United',
	'Uzbekistan',
	'VOEPASS',
	'Virgin Atlantic',
	'Virgin Australia',
	'Vistara',
	'Viva Air',
	'VivaAerobus',
	'Volaris',
	'Volotea',
	'Vueling',
	'WestJet',
	'Wingo',
	'Wizz Air',
	'XiamenAir',
	'Zhejiang Loong Airlines',
	'easyJet',
	'easyJet Europe Airline',
	'flydubai',
	'jetSMART')
all_airlines <- trimws(all_airlines, "left")


# Remove "X." from all column names
names(flights_encoded) <- gsub("^X\\.", "", names(flights_encoded))
# Replace "." with blank space in column names
names(flights_encoded) <- gsub("\\.", " ", names(flights_encoded))







# Step 1: Identify columns corresponding to airlines in all_airlines vector
airline_columns <- grep(paste(all_airlines, collapse = "|"), names(flights_encoded))

# Step 2: Filter out airlines not present in popular_airlines vector
airlines_to_remove <- setdiff(all_airlines[airline_columns], popular_airlines)

# Step 3: Remove corresponding columns from flights_encoded
flights_encoded <- flights_encoded[, !grepl(paste(airlines_to_remove, collapse = "|"), names(flights_encoded))]

# Alternatively, you can remove the columns using the airline_columns directly:
#flights_encoded <- flights_encoded[, -airline_column]
#unique(names(flights_encoded))

# Remove dots followed by numbers from column names
names(flights_encoded) <- gsub("\\.\\d+", "", names(flights_encoded), perl = TRUE)

# Now select columns based on airline names list
airline_columns <- intersect(names(flights_encoded), all_airlines)
# Function to take maximum across columns


# Convert data frame to a matrix
data_matrix <- as.matrix(flights_encoded)

# Get unique column names
unique_names <- unique(names(flights_encoded))

# Initialize a matrix for results
result_matrix <- matrix(nrow = nrow(data_matrix), ncol = length(unique_names))
colnames(result_matrix) <- unique_names

# Loop through each unique column name
for (name in unique_names) {
	# Identify columns that match the current name
	cols <- which(names(flights_encoded) == name)
	
	# Calculate the maximum value across these columns for each row
	result_matrix[, name] <- apply(data_matrix[, cols, drop = FALSE], 1, max)
}

# Convert the result matrix back to a data frame
result_df <- as.data.frame(result_matrix)

options(java.parameters = "-Xmx4g") # Set maximum heap size to 4 gigabytes
library("xlsx")
write.xlsx2(result_df, "flights_clean2.xlsx", sheetName = "Sheet1",
						col.names = TRUE, row.names = FALSE, append = FALSE)

saveRDS(result_df, "flights_clean.rds")



